# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script: phpunit --configuration phpunit.xml --coverage-text
